### ISSUE TITLE
MIT license incompatible with libCZI (?)

### ISSUE THREAD

**Issue by cgohlke** [elhuhdron/pylibczi#1]
I think the [MIT license used for pylibczi](https://github.com/elhuhdron/pylibczi/blob/master/LICENSE) is incompatible with the [GPL3 license used by libczi](https://github.com/zeiss-microscopy/libCZI/blob/master/LICENSE). GPL3 means that derivative work can only be distributed under the same license terms. Hence binaries for pylibczi and software using pylibczi must be distributed under GPL3.

**Comment by elhuhdron** [comment]
I'm a total noob regarding licensing issues; but it appears you are correct. I will update the pylibczi license to GPL3.
